### ISSUE TITLE
Przyciemnianie się obiektów hiperłączy

### ISSUE THREAD

**Issue by whatkindofmilkuare** [whatkindofmilkuare/moBILETv2#1]
Gdy kliknie się na obiekt który cofa do poprzedniej strony obraz który jest hiperłączem przyciemnia się

**Comment by whatkindofmilkuare** [comment]
a:hover img,
a:focus img,
a:active img {
    filter: none; /* Usuwa ewentualny filtr */
    opacity: 1;   /* Usuwa zmianę przezroczystości */
}

**Comment by whatkindofmilkuare** [comment]
'''
a:hover img,
a:focus img,
a:active img {
    filter: none; /* Usuwa ewentualny filtr */
    opacity: 1;   /* Usuwa zmianę przezroczystości */
} 
'''

**Comment by whatkindofmilkuare** [comment]
```css
a:hover img,
a:focus img,
a:active img {
    filter: none; /* Usuwa ewentualny filtr */
    opacity: 1;   /* Usuwa zmianę przezroczystości */
}
```

**Comment by whatkindofmilkuare** [comment]
```css
img {
    -webkit-tap-highlight-color: transparent; /* Wyłącza efekt tapnięcia na mobilnych */
}
```
